name: Build Kivy Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build-android:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" /usr/local/lib/android/sdk/ndk/
        sudo apt-get clean
        df -h

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            gettext \
            libltdl-dev \
            libffi-dev \
            libssl-dev

    - name: Install Buildozer and Cython
      run: |
        pip3 install --user --upgrade "buildozer>=1.5.0" "Cython==0.29.33"
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache Buildozer dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Build APK with Buildozer
      run: |
        # 确保目录存在
        mkdir -p bin
        
        # 接受Android SDK许可证
        if [ -d "$ANDROID_HOME/cmdline-tools/latest/bin" ]; then
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        fi
        
        # 构建APK
        buildozer -v android debug
      env:
        BUILDOZER_ALLOW_ORG_NAME_START_WITH_NUMBER: 1
      timeout-minutes: 60

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: bin/*.apk
        retention-days: 30

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          buildozer.log
          .buildozer/android/platform/build-*/build.log
        retention-days: 7
